parameters:
  # EMA parameters
  ema_fast_length: 20
  ema_slow_length: 50
  
  # Bollinger Bands parameters
  bb_length: 20
  bb_stds: 2  # Integer like Freqtrade
  
  # RSI parameters
  rsi_length: 14
  rsi_overbought: 50  # From sell_params in Freqtrade
  rsi_oversold: 35    # From buy_params in Freqtrade
  
  # Choppiness Index parameters
  chop_length: 14
  chop_trending_threshold: 38.0  # From buy_params in Freqtrade
  chop_choppy_threshold: 62.0    # From buy_params in Freqtrade
  
  # ATR parameters
  atr_length: 14
  atr_mult_trend: 3.0
  atr_mult_chop: 1.8
  
  # Portfolio parameters
  bidirectional: true
  initial_cash: 10000
  fee: 0.0005
  primary_timeframe: "1H"
  
  # Data source: "csv" or "ccxt" (simple choice)
  data_source: "ccxt"

optimization_grid:
  ema_fast_length: [15, 20, 25]
  ema_slow_length: [40, 50, 60]
  chop_trending_threshold: [30, 35, 38, 42]
  chop_choppy_threshold: [58, 62, 65, 70]
  rsi_oversold: [25, 30, 35]
  rsi_overbought: [65, 70, 75]
  bb_stds: [1.5, 2.0, 2.5]
  atr_mult_trend: [2.0, 2.5, 3.0, 3.5]
  atr_mult_chop: [1.5, 1.8, 2.0, 2.2]

data_requirements:
  required_timeframes: ["1H"]
  required_columns: ["open", "high", "low", "close", "volume"]

csv_path:
  - "data/EURUSD_1H_2009-2025.csv"
  - "data/BTCUSD_1h_2011-2025.csv"