parameters:
  kalman_q: 0.00001
  kalman_r: 0.001
  ma_period: 225
  target_volatility: 0.25
  vol_window: 10
  initial_cash: 10000
  fee: 0.0004

csv_path: "data/4h_NASDAQ.csv"

optimization_grid:
  kalman_q: [0.000001, 0.0001, 0.00001]
  kalman_r: [0.0001, 0.01, 0.001]
  ma_period: [100, 300, 25]
  target_volatility: [0.15, 0.35, 0.05]
  vol_window: [5, 25, 5]
